# Generated by Django 5.1.6 on 2025-07-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measurement",
            old_name="pm_value",
            new_name="pm_10_value",
        ),
        migrations.AddField(
            model_name="measurement",
            name="co2_value",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measurement",
            name="humidity",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measurement",
            name="pm_1_value",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measurement",
            name="pm_2_5_value",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measurement",
            name="temperature",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measurement",
            name="voc_value",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
